apiVersion: apps/v1
kind: Deployment

metadata:
  name: spring-deployment
  labels:
    app: spring

spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend-app

  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: spring-container
          image: springio/gs-spring-boot-docker
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
